Fix issues in projects command
backdrop-contrib/b pull request #137
Opened 2021-03-05 21:02 UTC by bugfolder

b pmi <project> issued warnings for missing .info fields and erroneous formatting with required/requires fields. This fixes those.

2021-03-18 03:42 UTC, BWPanda requested changes
@bugfolder Nearly there with this PR. Just few small changes please.

2021-03-18 03:42 UTC, ghost commented on commands/projects.b.inc
> +        array('value' => !empty($module->info['project']) ? $module->info['project'] : ''),
There are conflicts with the PR, which I believe are because I already added this part into the main branch when I was working on tests. Rebasing will remove this and fix conflicts.

2021-03-18 03:42 UTC, ghost commented on commands/projects.b.inc
> +      );!
Please fix this '!' in the wrong place.

2021-03-18 22:05 UTC, BWPanda commented
@bugfolder Something's gone wrong with the merging/update. Now the PR is trying to re-add all the recent changes that were already made... Maybe a quick/easy solution to your git issues is just to re-fork the current Bee project, then re-add your changes? But I guess that depends on the extent of your changes...

2021-03-18 22:32 UTC, bugfolder commented
OK, I'm going to just blow away my current repository (which started life as "b"), re-fork from bee, and then regenerate the PRs.

I did eventually find that I could push via Github Desktop; so at least the token woes seem to be fixed.

2021-03-19 10:56 UTC, BWPanda commented
Closing in favour of https://github.com/backdrop-contrib/bee/pull/144

2021-03-19 10:56 UTC, closed without merging