Issue #22: Provides a verbose option that prevents bee from outputting warnings…
backdrop-contrib/b pull request #184
Opened 2022-04-25 15:59 UTC by rbargerhuff

2022-05-17 11:41 UTC, BWPanda requested changes
One very small fix.

2022-05-17 11:41 UTC, BWPanda commented on includes/globals.inc
> +// A boolean indicating whether 'verbose' mode is enabled.
Best to copy syntax from other examples above:

```suggestion
// A boolean indicating whether `Verbose` mode is enabled.
```

2022-08-19 15:45 UTC, rbargerhuff commented
My collegue and I who originally made this Pull Request noticed that the change made by @BWPanda had not been commited to the main branch and we are wondering how this request can be included.

2022-08-19 15:46 UTC, rbargerhuff reviewed
This change is great. Thank you!

2022-10-13 07:42 UTC, yorkshire-pudding commented
Hi @rbargerhuff - I'm sorry this wasn't merged earlier.  Would you be willing to to a rebase of your PR so that it can be merged as it is currently causing a conflict due to recent changes for PHP 8.1 compatibility?
In particular, this line in `bee.php`
```php
function bee_error_handler($errno, $message, $filename, $line, $context) {
```
has changed to
```php
function bee_error_handler($errno, $message, $filename, $line, $context = NULL) {
```

And because your branch is based on an older version, there is a conflict there.
This looks like a great addition so would be great to get it in.

2022-11-18 21:00 UTC, rbargerhuff commented
Abandoning this PR since it is no longer applicable.

2022-11-18 21:00 UTC, closed without merging